theme: jekyll-theme-slate

title: UA Research Computing
description: HPC Examples
relative_links:
  enabled: true
  collections: true
  markdown: kramdown
  kramdown:
    input: GFM
    syntax_highlighter: rouge
plugins:
  - jemoji
 
