theme: jekyll-theme-slate

title: UA Research Computing
description: HPC Examples
relative_links:
  enabled: true
  collections: true
include:
  - PBS-Scripts/Array-and-Parallel/README.md
  - PBS-Scripts/Array-and-Parallel/Basic_Array_Job.md
  - PBS-Scripts/Array-and-Parallel/Basic_Array_Job.pbs
