theme: jekyll-theme-slate

title: UA Research Computing
description: HPC Examples
relative_links:
  enabled: true
  collections: true
include:
  - Images/BlackHoleMashup_TextOverlap.png
  - PBS-Scripts/Array-and-Parallel/README.md
  - PBS-Scripts/Array-and-Parallel/Basic-Array-Job/README.md
  - PBS-Scripts/Array-and-Parallel/Array-Read-Filenames/README.md
  - PBS-Scripts/Array-and-Parallel/Array-Read-Parameters/README.md
  - PBS-Scripts/Array-and-Parallel/Basic-Parallel-Job/README.md
  - PBS-Scripts/Array-and-Parallel/Array-and-Parallel/README.md
 
