theme: jekyll-theme-slate

title: UA Research Computing
description: HPC Examples
relative_links:
  enabled: true
  collections: true
include:
  - Images/BlackHoleMashup_TextOverlap.png
  - PBS-Scripts/Array-and-Parallel/README.md
  - PBS-Scripts/Array-and-Parallel/Basic-Array-Job/README.md
  - PBS-Scripts/Array-and-Parallel/Basic-Array-Job/Basic_Array_Job.pbs
  - PBS-Scripts/Array-and-Parallel/Array-Read-Filenames/Sample_Array_Read_Filenames.md
  - PBS-Scripts/Array-and-Parallel/Array-Read-Filenames/Sample_Array_Read_Filenames.pbs
  - PBS-Scripts/Array-and-Parallel/Array-Read-Filenames/InputFiles
  - PBS-Scripts/Array-and-Parallel/Array-Read-Parameters/Sample_Array_Input_Parameters.md
  - PBS-Scripts/Array-and-Parallel/Array-Read-Parameters/Sample_Array_Input_Parameters.pbs
  - PBS-Scripts/Array-and-Parallel/Array-Read-Parameters/input_parameters
  - PBS-Scripts/Array-and-Parallel/Basic-Parallel-Job/Basic_Parallel_Job.md
  - PBS-Scripts/Array-and-Parallel/Basic-Parallel-Job/Basic_Parallel_Job.pbs
  - PBS-Scripts/Array-and-Parallel/Array-and-Parallel/Sample_Array_with_GNUParallel.md
  - PBS-Scripts/Array-and-Parallel/Array-and-Parallel/Sample_Array_with_GNUParallel.md
 
